In [21]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/data.csv",encoding = "latin-1")

In [22]:
print("Shape",df.shape)

Shape (541909, 8)

In [23]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [24]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [25]:
#dropping the missing rows in which customer id is missing
df.dropna(subset=['CustomerID'],inplace = True)

In [26]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [27]:
df.sample(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
96908,544597,21204,DAISIES HONEYCOMB GARLAND,1,2/21/2011 17:42,1.65,16014.0,United Kingdom
78787,542898,20762,GREEN FERN SKETCHBOOK,1,2/1/2011 14:01,3.75,16110.0,United Kingdom
155370,549984,22138,BAKING SET 9 PIECE RETROSPOT,4,4/13/2011 15:57,4.95,15147.0,United Kingdom
333552,566200,22470,HEART OF WICKER LARGE,2,9/9/2011 14:14,2.95,16910.0,United Kingdom
263555,560018,21212,PACK OF 72 RETROSPOT CAKE CASES,1,7/14/2011 12:52,0.55,15987.0,United Kingdom
49771,540531,21066,VINTAGE RED MUG,1,1/9/2011 14:03,1.25,16549.0,United Kingdom
413073,572306,23237,SET OF 4 KNICK KNACK TINS LEAF,1,10/23/2011 15:11,4.15,17841.0,United Kingdom
204188,554640,21936,RED RETROSPOT PICNIC BAG,20,5/25/2011 12:06,2.95,14680.0,United Kingdom
81296,543118,22595,GINGHAM HEART DECORATION,12,2/3/2011 13:31,0.85,13842.0,United Kingdom
149198,549279,22353,LUNCH BOX WITH CUTLERY FAIRY CAKES,1,4/7/2011 13:16,2.55,16469.0,United Kingdom

In [28]:
# Check for cancelled orders
cancelled = df[df['InvoiceNo'].astype(str).str.startswith('C')]
print("Cancelled orders found:", len(cancelled))

Cancelled orders found: 8905

In [29]:
#remove cancelled order if any
df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]

In [30]:
#removing the bad quantites and prices
df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]

In [31]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  397884.000000  397884.000000  397884.000000
mean       12.988238       3.116488   15294.423453
std       179.331775      22.097877    1713.141560
min         1.000000       0.001000   12346.000000
25%         2.000000       1.250000   13969.000000
50%         6.000000       1.950000   15159.000000
75%        12.000000       3.750000   16795.000000
max     80995.000000    8142.750000   18287.000000

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 397884 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397884 non-null  object
 1   StockCode    397884 non-null  object
 2   Description  397884 non-null  object
 3   Quantity     397884 non-null  int64
 4   InvoiceDate  397884 non-null  object
 5   UnitPrice    397884 non-null  float64
 6   CustomerID   397884 non-null  float64
 7   Country      397884 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 27.3+ MB

In [33]:
#fix the data type of the Invoice data because it is object
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [34]:
df['CustomerID'] = df['CustomerID'].astype(int).astype(str)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 397884 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397884 non-null  object
 1   StockCode    397884 non-null  object
 2   Description  397884 non-null  object
 3   Quantity     397884 non-null  int64
 4   InvoiceDate  397884 non-null  datetime64[ns]
 5   UnitPrice    397884 non-null  float64
 6   CustomerID   397884 non-null  object
 7   Country      397884 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 27.3+ MB

In [36]:
#revenue
df['Revenue'] = df['Quantity'] * df['UnitPrice']

In [37]:
df['Year']      = df['InvoiceDate'].dt.year
df['Month']     = df['InvoiceDate'].dt.month
df['YearMonth'] = df['InvoiceDate'].dt.to_period('M').astype(str)

In [38]:
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month,YearMonth
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12,2010-12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010,12,2010-12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,2010-12

In [39]:
df.drop_duplicates(inplace=True)

In [40]:
df.to_csv('../data/clean_data.csv', index=False)